 spring:
 datasource:
 url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
 username: Péricles
 password: Periclesdev

 jpa:
 show-sql: true
 hibernate:
 ddl-auto: update
 properties:
 hibernate_format_sql: true

 logging:
  level:
    org:
      hibernate:
        type: trace
